### ISSUE TITLE
Load - apply Look with template builder

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/openpype-custom-plugins#2]
In GitLab by @support-bot on Apr 21, 2023, 11:05

> From...

 The template builder make it seam possible that we can load / apply look to asset but unfortunately, it's not doable

Some fonctionality seam there, like the 'order' for exemple, and look family choice

We want to be able to load the published look for the assets linked to the shot/entity (if they exist)

 by template builder and apply them with template builder

With this, we could have a lighting shot totally built ready to light

![image](https://user-images.githubusercontent.com/68907585/235690281-d4a7e57d-7ab0-4dd2-ad2d-cdeef90d931d.png)

## Softwares concerned

Maya, Fix

**Comment by BenSouchet** [comment]
Closing it.
